In [118]:
import pandas as pd # Data structure for CSV
import re # Regular Expressions
from sklearn.feature_selection import VarianceThreshold
import numpy as np # Numpy need no introduction
from datetime import datetime as dt
from sklearn.model_selection import GroupShuffleSplit, GroupKFold, cross_val_score
from sklearn.pipeline import Pipeline
import xgboost as xgb
from sklearn.preprocessing import LabelEncoder
from sklearn.base import BaseEstimator, TransformerMixin


the_now = dt.now()
now = the_now.strftime("%Y-%m-%d_%H:%M:%S")

df = pd.read_csv('../dataset/full.csv')
prev_df = pd.read_csv('../dataset/full.csv')
df_columns = df.columns.tolist()
df_cleaned = pd.DataFrame()
prev_df_columns = []

df.head()

,tBodyAcc-mean()-X,tBodyAcc-mean()-Y,tBodyAcc-mean()-Z,tBodyAcc-std()-X,tBodyAcc-std()-Y,tBodyAcc-std()-Z,tBodyAcc-mad()-X,tBodyAcc-mad()-Y,tBodyAcc-mad()-Z,tBodyAcc-max()-X,...,fBodyBodyGyroJerkMag-kurtosis(),"angle(tBodyAccMean,gravity)","angle(tBodyAccJerkMean),gravityMean)","angle(tBodyGyroMean,gravityMean)","angle(tBodyGyroJerkMean,gravityMean)","angle(X,gravityMean)","angle(Y,gravityMean)","angle(Z,gravityMean)",subject,Activity
0,0.288585,-0.020294,-0.132905,-0.995279,-0.983111,-0.913526,-0.995112,-0.983185,-0.923527,-0.934724,...,-0.710304,-0.112754,0.030400,-0.464761,-0.018446,-0.841247,0.179941,-0.058627,1,STANDING
1,0.278419,-0.016411,-0.123520,-0.998245,-0.975300,-0.960322,-0.998807,-0.974914,-0.957686,-0.943068,...,-0.861499,0.053477,-0.007435,-0.732626,0.703511,-0.844788,0.180289,-0.054317,1,STANDING
2,0.279653,-0.019467,-0.113462,-0.995380,-0.967187,-0.978944,-0.996520,-0.963668,-0.977469,-0.938692,...,-0.760104,-0.118559,0.177899,0.100699,0.808529,-0.848933,0.180637,-0.049118,1,STANDING
3,0.279174,-0.026201,-0.123283,-0.996091,-0.983403,-0.990675,-0.997099,-0.982750,-0.989302,-0.938692,...,-0.482845,-0.036788,-0.012892,0.640011,-0.485366,-0.848649,0.181935,-0.047663,1,STANDING
4,0.276629,-0.016570,-0.115362,-0.998139,-0.980817,-0.990482,-0.998321,-0.979672,-0.990441,-0.942469,...,-0.699205,0.123320,0.122542,0.693578,-0.615971,-0.847865,0.185151,-0.043892,1,STANDING

## Some functions

In [119]:
# 2. Multicollinearity High Correlation Filter (>0.95)
class CorrelationFilter(BaseEstimator, TransformerMixin):
    def __init__(self, threshold=0.95):
        self.threshold = threshold
        self.to_drop_ = []

    def fit(self, X, y=None):
        # Calculate pairwise correlations strictly on training data
        df_x = pd.DataFrame(X) if not isinstance(X, pd.DataFrame) else X
        corr_matrix = df_x.corr().abs()
        upper_tri = corr_matrix.where(
            np.triu(np.ones(corr_matrix.shape), k=1).astype(bool)
        )
        self.to_drop_ = [
            col for col in upper_tri.columns 
            if any(upper_tri[col] > self.threshold)
        ]
        return self

    def transform(self, X):
        df_x = pd.DataFrame(X) if not isinstance(X, pd.DataFrame) else X
        return df_x.drop(columns=self.to_drop_)

In [120]:
def compare_df():    
    if df_cleaned.empty:
        return
    df_cleaned_columns = df_cleaned.columns.tolist()
    prev_df_columns = prev_df.columns.tolist()

    diff_list_total = list(set(df_columns) - set(df_cleaned_columns))
    diff_list = list(list(set(prev_df_columns) - set(df_cleaned_columns)))

    df_columns_count = len(df_columns)
    df_cleaned_columns_count = len(df_cleaned_columns)
    prev_df_columns_count = len(prev_df_columns)

    total_removed_features = df_columns_count - df_cleaned_columns_count
    this_step_removed_features = prev_df_columns_count - df_cleaned_columns_count

    print("Features excluded (in total):")
    print(diff_list_total)
    print('='*50)
    print("Features excluded (this step):")
    print(diff_list)
    print('='*50)
    print("Removed total: " + str(df_columns_count) + " ---> " + str(df_cleaned_columns_count) + " features")
    print("Total feature removal count: " + str(total_removed_features))
    print('='*50)
    print("Removed this step: " + str(prev_df_columns_count) + " ---> " + str(df_cleaned_columns_count) + " features")
    print("Feature removal this step count: " + str(this_step_removed_features))

# Feature extraction/selection

First, we remove features that contain duplicate data to another.

In [121]:
df_cleaned = df.T.drop_duplicates(keep='first').T

df_cleaned.head()

,tBodyAcc-mean()-X,tBodyAcc-mean()-Y,tBodyAcc-mean()-Z,tBodyAcc-std()-X,tBodyAcc-std()-Y,tBodyAcc-std()-Z,tBodyAcc-mad()-X,tBodyAcc-mad()-Y,tBodyAcc-mad()-Z,tBodyAcc-max()-X,...,fBodyBodyGyroJerkMag-kurtosis(),"angle(tBodyAccMean,gravity)","angle(tBodyAccJerkMean),gravityMean)","angle(tBodyGyroMean,gravityMean)","angle(tBodyGyroJerkMean,gravityMean)","angle(X,gravityMean)","angle(Y,gravityMean)","angle(Z,gravityMean)",subject,Activity
0,0.288585,-0.020294,-0.132905,-0.995279,-0.983111,-0.913526,-0.995112,-0.983185,-0.923527,-0.934724,...,-0.710304,-0.112754,0.0304,-0.464761,-0.018446,-0.841247,0.179941,-0.058627,1,STANDING
1,0.278419,-0.016411,-0.12352,-0.998245,-0.9753,-0.960322,-0.998807,-0.974914,-0.957686,-0.943068,...,-0.861499,0.053477,-0.007435,-0.732626,0.703511,-0.844788,0.180289,-0.054317,1,STANDING
2,0.279653,-0.019467,-0.113462,-0.99538,-0.967187,-0.978944,-0.99652,-0.963668,-0.977469,-0.938692,...,-0.760104,-0.118559,0.177899,0.100699,0.808529,-0.848933,0.180637,-0.049118,1,STANDING
3,0.279174,-0.026201,-0.123283,-0.996091,-0.983403,-0.990675,-0.997099,-0.98275,-0.989302,-0.938692,...,-0.482845,-0.036788,-0.012892,0.640011,-0.485366,-0.848649,0.181935,-0.047663,1,STANDING
4,0.276629,-0.01657,-0.115362,-0.998139,-0.980817,-0.990482,-0.998321,-0.979672,-0.990441,-0.942469,...,-0.699205,0.12332,0.122542,0.693578,-0.615971,-0.847865,0.185151,-0.043892,1,STANDING

In [122]:
compare_df()
prev_df = df_cleaned

Features excluded (in total):
['tGravityAccMag-mad()', 'tGravityAccMag-min()', 'tGravityAccMag-arCoeff()2', 'tGravityAccMag-arCoeff()1', 'tGravityAccMag-mean()', 'fBodyBodyAccJerkMag-sma()', 'tGravityAccMag-entropy()', 'tGravityAccMag-max()', 'fBodyAccMag-sma()', 'tGravityAccMag-arCoeff()4', 'tBodyAccMag-sma()', 'tBodyGyroJerkMag-sma()', 'tGravityAccMag-arCoeff()3', 'tGravityAccMag-sma()', 'tGravityAccMag-std()', 'fBodyBodyGyroMag-sma()', 'tGravityAccMag-iqr()', 'tGravityAccMag-energy()', 'tBodyAccJerkMag-sma()', 'tBodyGyroMag-sma()', 'fBodyBodyGyroJerkMag-sma()']
==================================================
Features excluded (this step):
['tGravityAccMag-mad()', 'tGravityAccMag-min()', 'tGravityAccMag-arCoeff()2', 'tGravityAccMag-arCoeff()1', 'tGravityAccMag-mean()', 'fBodyBodyAccJerkMag-sma()', 'tGravityAccMag-entropy()', 'tGravityAccMag-max()', 'fBodyAccMag-sma()', 'tGravityAccMag-arCoeff()4', 'tBodyAccMag-sma()', 'tBodyGyroJerkMag-sma()', 'tGravityAccMag-arCoeff()3', 'tGravityAccMag-sma()', 'tGravityAccMag-std()', 'fBodyBodyGyroMag-sma()', 'tGravityAccMag-iqr()', 'tGravityAccMag-energy()', 'tBodyAccJerkMag-sma()', 'tBodyGyroMag-sma()', 'fBodyBodyGyroJerkMag-sma()']
==================================================
Removed total: 563 ---> 542 features
Total feature removal count: 21
==================================================
Removed this step: 563 ---> 542 features
Feature removal this step count: 21

563 ---> 542 features

### Then, we consider what type of feature:
In the dataset, we've got two types of recorded data:
- t-* features: Raw time-series signals recorded at 50hz
- f-* features: Signals transformed using Fast Fourier Transform

There are mathematical functions that have been applied to numerous features, and in some cases the "t" and "p" version of these functions yield no new information.

## Gemini breakdown because my dumbass dont know shit about physics:

### What you can safely remove:
f*-mean():
This function calculates the plain arithmetic mean of the Fourier amplitudes across all frequency bins. For primary acceleration, this is mathematically tied to the baseline time-domain average (tBodyAcc-mean()) or overall signal power. Dropping these across the board will cause almost zero loss in model accuracy because the time-domain equivalent (t) already captures the signal's overall magnitude

f*.max() + f*.min():
Why f is redundant/invalid: In the time domain, tBodyAcc-max()-X tells you the maximum G-force impulse experienced during a movement step. In the frequency domain, fBodyAcc-max()-X simply tells you the amplitude of the single strongest frequency peak. While peak frequency amplitude is informative, peak frequency intensity is already captured far more comprehensively by fBodyAcc-maxFreqInd (index of peak frequency) or fBodyAcc-energy()

f*.std() + f*.iqr() + f*.energy():
Why f is redundant/invalid: Thanks to Parseval’s Theorem, the total energy (variance) of a signal in the time domain is mathematically equal to the total energy of the signal in the frequency domain. Calculating dispersion statistics like std() or iqr() on the time signal tBodyAcc directly measures movement volatility. Doing the exact same calculation on the FFT bins (fBodyAcc-std()) simply measures how spread out the frequency amplitudes are, which strongly co-varies with time-domain variance.

Source for Parseval's Theorem and its valid application in sensory data feature extraction: 
 10.1109/access.2020.2996576

In [123]:
total_features = df_cleaned.columns.tolist()

# Let's remove all f*-mean():
regex = r"^f.*-mean\(\)"
features_to_remove = [i for i in total_features if re.search(regex, i)]
df_cleaned = df_cleaned.drop(columns=features_to_remove)

# Remove all f*-max():
regex = r"^f.*-max\(\)"
features_to_remove = []
features_to_remove = [i for i in total_features if re.search(regex, i)]
df_cleaned = df_cleaned.drop(columns=features_to_remove)

# Remove all f*-min():
regex = r"^f.*-min\(\)"
features_to_remove = []
features_to_remove = [i for i in total_features if re.search(regex, i)]
df_cleaned = df_cleaned.drop(columns=features_to_remove)

df_cleaned.head()

,tBodyAcc-mean()-X,tBodyAcc-mean()-Y,tBodyAcc-mean()-Z,tBodyAcc-std()-X,tBodyAcc-std()-Y,tBodyAcc-std()-Z,tBodyAcc-mad()-X,tBodyAcc-mad()-Y,tBodyAcc-mad()-Z,tBodyAcc-max()-X,...,fBodyBodyGyroJerkMag-kurtosis(),"angle(tBodyAccMean,gravity)","angle(tBodyAccJerkMean),gravityMean)","angle(tBodyGyroMean,gravityMean)","angle(tBodyGyroJerkMean,gravityMean)","angle(X,gravityMean)","angle(Y,gravityMean)","angle(Z,gravityMean)",subject,Activity
0,0.288585,-0.020294,-0.132905,-0.995279,-0.983111,-0.913526,-0.995112,-0.983185,-0.923527,-0.934724,...,-0.710304,-0.112754,0.0304,-0.464761,-0.018446,-0.841247,0.179941,-0.058627,1,STANDING
1,0.278419,-0.016411,-0.12352,-0.998245,-0.9753,-0.960322,-0.998807,-0.974914,-0.957686,-0.943068,...,-0.861499,0.053477,-0.007435,-0.732626,0.703511,-0.844788,0.180289,-0.054317,1,STANDING
2,0.279653,-0.019467,-0.113462,-0.99538,-0.967187,-0.978944,-0.99652,-0.963668,-0.977469,-0.938692,...,-0.760104,-0.118559,0.177899,0.100699,0.808529,-0.848933,0.180637,-0.049118,1,STANDING
3,0.279174,-0.026201,-0.123283,-0.996091,-0.983403,-0.990675,-0.997099,-0.98275,-0.989302,-0.938692,...,-0.482845,-0.036788,-0.012892,0.640011,-0.485366,-0.848649,0.181935,-0.047663,1,STANDING
4,0.276629,-0.01657,-0.115362,-0.998139,-0.980817,-0.990482,-0.998321,-0.979672,-0.990441,-0.942469,...,-0.699205,0.12332,0.122542,0.693578,-0.615971,-0.847865,0.185151,-0.043892,1,STANDING

In [124]:
compare_df()
prev_df = df_cleaned

Features excluded (in total):
['tGravityAccMag-mad()', 'fBodyAccMag-mean()', 'tGravityAccMag-min()', 'tGravityAccMag-arCoeff()2', 'fBodyGyro-max()-Y', 'fBodyAccJerk-max()-Y', 'tGravityAccMag-arCoeff()1', 'tGravityAccMag-mean()', 'fBodyGyro-mean()-Z', 'fBodyBodyGyroJerkMag-min()', 'fBodyBodyAccJerkMag-mean()', 'fBodyBodyAccJerkMag-min()', 'fBodyBodyAccJerkMag-max()', 'fBodyGyro-min()-X', 'fBodyGyro-max()-X', 'fBodyAcc-min()-Z', 'fBodyBodyAccJerkMag-sma()', 'tGravityAccMag-entropy()', 'tGravityAccMag-max()', 'fBodyAcc-max()-Z', 'fBodyGyro-max()-Z', 'fBodyAccMag-max()', 'fBodyAccMag-min()', 'fBodyGyro-min()-Z', 'fBodyAccMag-sma()', 'fBodyAcc-min()-Y', 'fBodyBodyGyroMag-min()', 'fBodyBodyGyroJerkMag-mean()', 'tGravityAccMag-arCoeff()4', 'fBodyGyro-mean()-Y', 'tBodyAccMag-sma()', 'tBodyGyroJerkMag-sma()', 'fBodyAcc-min()-X', 'fBodyAccJerk-min()-Z', 'fBodyAcc-mean()-Y', 'fBodyAccJerk-max()-X', 'fBodyAcc-mean()-Z', 'fBodyAcc-max()-Y', 'fBodyBodyGyroMag-max()', 'fBodyBodyGyroJerkMag-max()', 'fBodyAccJerk-mean()-X', 'fBodyAcc-mean()-X', 'tGravityAccMag-arCoeff()3', 'fBodyAccJerk-max()-Z', 'tGravityAccMag-sma()', 'tGravityAccMag-std()', 'fBodyGyro-min()-Y', 'tGravityAccMag-iqr()', 'fBodyBodyGyroMag-sma()', 'fBodyAccJerk-mean()-Y', 'fBodyAcc-max()-X', 'fBodyAccJerk-min()-Y', 'tGravityAccMag-energy()', 'fBodyGyro-mean()-X', 'tBodyAccJerkMag-sma()', 'fBodyAccJerk-min()-X', 'fBodyBodyGyroMag-mean()', 'tBodyGyroMag-sma()', 'fBodyBodyGyroJerkMag-sma()', 'fBodyAccJerk-mean()-Z']
==================================================
Features excluded (this step):
['fBodyAccMag-mean()', 'fBodyGyro-max()-Y', 'fBodyAccJerk-max()-Y', 'fBodyGyro-mean()-Z', 'fBodyBodyGyroJerkMag-min()', 'fBodyBodyAccJerkMag-mean()', 'fBodyBodyAccJerkMag-min()', 'fBodyBodyAccJerkMag-max()', 'fBodyGyro-min()-X', 'fBodyGyro-max()-X', 'fBodyAcc-min()-Z', 'fBodyAcc-max()-Z', 'fBodyGyro-max()-Z', 'fBodyAccMag-max()', 'fBodyAccMag-min()', 'fBodyGyro-min()-Z', 'fBodyAcc-min()-Y', 'fBodyBodyGyroMag-min()', 'fBodyBodyGyroJerkMag-mean()', 'fBodyGyro-mean()-Y', 'fBodyAcc-min()-X', 'fBodyAccJerk-min()-Z', 'fBodyAcc-mean()-Y', 'fBodyAccJerk-max()-X', 'fBodyAcc-mean()-Z', 'fBodyAcc-max()-Y', 'fBodyBodyGyroMag-max()', 'fBodyBodyGyroJerkMag-max()', 'fBodyAccJerk-mean()-X', 'fBodyAcc-mean()-X', 'fBodyAccJerk-max()-Z', 'fBodyGyro-min()-Y', 'fBodyAccJerk-mean()-Y', 'fBodyAcc-max()-X', 'fBodyAccJerk-min()-Y', 'fBodyGyro-mean()-X', 'fBodyAccJerk-min()-X', 'fBodyBodyGyroMag-mean()', 'fBodyAccJerk-mean()-Z']
==================================================
Removed total: 563 ---> 503 features
Total feature removal count: 60
==================================================
Removed this step: 542 ---> 503 features
Feature removal this step count: 39

542 ---> 503 features

In [125]:
# Remove all f*"-energy" (excluding bandsEnergy)
regex = r"^f.*-energy\(\)"
features_to_remove = []
features_to_remove = [i for i in total_features if re.search(regex, i)]
df_cleaned = df_cleaned.drop(columns=features_to_remove)
df_cleaned.head()

,tBodyAcc-mean()-X,tBodyAcc-mean()-Y,tBodyAcc-mean()-Z,tBodyAcc-std()-X,tBodyAcc-std()-Y,tBodyAcc-std()-Z,tBodyAcc-mad()-X,tBodyAcc-mad()-Y,tBodyAcc-mad()-Z,tBodyAcc-max()-X,...,fBodyBodyGyroJerkMag-kurtosis(),"angle(tBodyAccMean,gravity)","angle(tBodyAccJerkMean),gravityMean)","angle(tBodyGyroMean,gravityMean)","angle(tBodyGyroJerkMean,gravityMean)","angle(X,gravityMean)","angle(Y,gravityMean)","angle(Z,gravityMean)",subject,Activity
0,0.288585,-0.020294,-0.132905,-0.995279,-0.983111,-0.913526,-0.995112,-0.983185,-0.923527,-0.934724,...,-0.710304,-0.112754,0.0304,-0.464761,-0.018446,-0.841247,0.179941,-0.058627,1,STANDING
1,0.278419,-0.016411,-0.12352,-0.998245,-0.9753,-0.960322,-0.998807,-0.974914,-0.957686,-0.943068,...,-0.861499,0.053477,-0.007435,-0.732626,0.703511,-0.844788,0.180289,-0.054317,1,STANDING
2,0.279653,-0.019467,-0.113462,-0.99538,-0.967187,-0.978944,-0.99652,-0.963668,-0.977469,-0.938692,...,-0.760104,-0.118559,0.177899,0.100699,0.808529,-0.848933,0.180637,-0.049118,1,STANDING
3,0.279174,-0.026201,-0.123283,-0.996091,-0.983403,-0.990675,-0.997099,-0.98275,-0.989302,-0.938692,...,-0.482845,-0.036788,-0.012892,0.640011,-0.485366,-0.848649,0.181935,-0.047663,1,STANDING
4,0.276629,-0.01657,-0.115362,-0.998139,-0.980817,-0.990482,-0.998321,-0.979672,-0.990441,-0.942469,...,-0.699205,0.12332,0.122542,0.693578,-0.615971,-0.847865,0.185151,-0.043892,1,STANDING

In [126]:
compare_df()
prev_df = df_cleaned

Features excluded (in total):
['fBodyBodyGyroMag-energy()', 'tGravityAccMag-mad()', 'tGravityAccMag-min()', 'fBodyAccMag-mean()', 'fBodyAccMag-energy()', 'tGravityAccMag-arCoeff()2', 'fBodyGyro-max()-Y', 'fBodyAccJerk-max()-Y', 'fBodyBodyAccJerkMag-energy()', 'fBodyBodyGyroJerkMag-energy()', 'tGravityAccMag-arCoeff()1', 'tGravityAccMag-mean()', 'fBodyGyro-mean()-Z', 'fBodyBodyGyroJerkMag-min()', 'fBodyBodyAccJerkMag-mean()', 'fBodyGyro-energy()-Y', 'fBodyBodyAccJerkMag-min()', 'fBodyBodyAccJerkMag-max()', 'fBodyGyro-energy()-X', 'fBodyGyro-min()-X', 'fBodyAcc-min()-Z', 'fBodyAcc-energy()-Z', 'fBodyBodyAccJerkMag-sma()', 'fBodyGyro-max()-X', 'tGravityAccMag-max()', 'fBodyAcc-max()-Z', 'tGravityAccMag-entropy()', 'fBodyGyro-max()-Z', 'fBodyAccMag-max()', 'fBodyAccMag-min()', 'fBodyGyro-min()-Z', 'fBodyAccMag-sma()', 'fBodyAcc-min()-Y', 'fBodyBodyGyroMag-min()', 'fBodyAccJerk-energy()-X', 'fBodyBodyGyroJerkMag-mean()', 'tGravityAccMag-arCoeff()4', 'fBodyGyro-mean()-Y', 'fBodyAcc-energy()-X', 'tBodyAccMag-sma()', 'tBodyGyroJerkMag-sma()', 'fBodyAcc-min()-X', 'fBodyAccJerk-min()-Z', 'fBodyAcc-mean()-Y', 'fBodyGyro-energy()-Z', 'fBodyAccJerk-max()-X', 'fBodyAcc-mean()-Z', 'fBodyAcc-max()-Y', 'fBodyAcc-energy()-Y', 'fBodyBodyGyroMag-max()', 'fBodyBodyGyroJerkMag-max()', 'fBodyAccJerk-mean()-X', 'fBodyAcc-mean()-X', 'tGravityAccMag-arCoeff()3', 'tGravityAccMag-sma()', 'fBodyAccJerk-max()-Z', 'fBodyAccJerk-energy()-Z', 'tGravityAccMag-std()', 'tGravityAccMag-iqr()', 'fBodyGyro-min()-Y', 'fBodyBodyGyroMag-sma()', 'fBodyAccJerk-mean()-Y', 'fBodyAcc-max()-X', 'fBodyAccJerk-min()-Y', 'tGravityAccMag-energy()', 'fBodyGyro-mean()-X', 'tBodyAccJerkMag-sma()', 'fBodyAccJerk-min()-X', 'fBodyBodyGyroMag-mean()', 'tBodyGyroMag-sma()', 'fBodyAccJerk-energy()-Y', 'fBodyBodyGyroJerkMag-sma()', 'fBodyAccJerk-mean()-Z']
==================================================
Features excluded (this step):
['fBodyBodyGyroMag-energy()', 'fBodyGyro-energy()-X', 'fBodyAcc-energy()-X', 'fBodyAcc-energy()-Z', 'fBodyAccJerk-energy()-Z', 'fBodyGyro-energy()-Y', 'fBodyAccMag-energy()', 'fBodyGyro-energy()-Z', 'fBodyAcc-energy()-Y', 'fBodyBodyAccJerkMag-energy()', 'fBodyBodyGyroJerkMag-energy()', 'fBodyAccJerk-energy()-Y', 'fBodyAccJerk-energy()-X']
==================================================
Removed total: 563 ---> 490 features
Total feature removal count: 73
==================================================
Removed this step: 503 ---> 490 features
Feature removal this step count: 13

542 ---> 490 features

# Variance filtering

We are to drop features that have x % sharing of same values. To prevent overfitting, we should split the dataset. To avoid individual subject's noise, we use subject-safe splitting. To validate the variance filtering, we use group k-fold cross validation.

In [127]:
gss = GroupShuffleSplit(n_splits=1, test_size=0.3, random_state=69)

# Get indices for train and test splits based on groups
train_idx, test_idx = next(gss.split(df, groups=df['subject']))

train_df = df.iloc[train_idx].copy()
test_df = df.iloc[test_idx].copy()

This should leave us with 21 train subjects, 9 test subjects.

In [128]:
X_train = train_df.drop(columns=['Activity', 'subject'])
y_train = train_df['Activity']
groups_train = train_df['subject']

# Setup GroupKFold cross-validation
gkf = GroupKFold(n_splits=5)

X_test = test_df.drop(columns=['Activity', 'subject'])

In [129]:
model = xgb.XGBClassifier(n_estimators=5000, max_depth=5, learning_rate=0.1, random_state=42)

label_encoder = LabelEncoder()

y_train = label_encoder.fit_transform(y_train)

pipeline = Pipeline([
    ('variance_threshold', VarianceThreshold(threshold=0.01)), # 2. Drop low variance (< 1%)
    ('corr_filter', CorrelationFilter(threshold=0.95))       # 3. Drop multicollinear features (> 0.95)
])

In [130]:
# Fit pipeline and extract features on Training data
X_train_extracted = pipeline.fit_transform(X_train)

# Transform Test data using trained parameters
X_test_extracted = pipeline.transform(X_test)

# Verify shapes
print(f"Original features: {X_train.shape[1]}")
print(f"Extracted features (after pipeline): {X_train_extracted.shape[1]}")

Original features: 561
Extracted features (after pipeline): 231

### Bring back 'Activity' and 'subject'
Let's bring the gang back together babey

In [131]:
print(df_cleaned.columns.tolist())

['tBodyAcc-mean()-X', 'tBodyAcc-mean()-Y', 'tBodyAcc-mean()-Z', 'tBodyAcc-std()-X', 'tBodyAcc-std()-Y', 'tBodyAcc-std()-Z', 'tBodyAcc-mad()-X', 'tBodyAcc-mad()-Y', 'tBodyAcc-mad()-Z', 'tBodyAcc-max()-X', 'tBodyAcc-max()-Y', 'tBodyAcc-max()-Z', 'tBodyAcc-min()-X', 'tBodyAcc-min()-Y', 'tBodyAcc-min()-Z', 'tBodyAcc-sma()', 'tBodyAcc-energy()-X', 'tBodyAcc-energy()-Y', 'tBodyAcc-energy()-Z', 'tBodyAcc-iqr()-X', 'tBodyAcc-iqr()-Y', 'tBodyAcc-iqr()-Z', 'tBodyAcc-entropy()-X', 'tBodyAcc-entropy()-Y', 'tBodyAcc-entropy()-Z', 'tBodyAcc-arCoeff()-X,1', 'tBodyAcc-arCoeff()-X,2', 'tBodyAcc-arCoeff()-X,3', 'tBodyAcc-arCoeff()-X,4', 'tBodyAcc-arCoeff()-Y,1', 'tBodyAcc-arCoeff()-Y,2', 'tBodyAcc-arCoeff()-Y,3', 'tBodyAcc-arCoeff()-Y,4', 'tBodyAcc-arCoeff()-Z,1', 'tBodyAcc-arCoeff()-Z,2', 'tBodyAcc-arCoeff()-Z,3', 'tBodyAcc-arCoeff()-Z,4', 'tBodyAcc-correlation()-X,Y', 'tBodyAcc-correlation()-X,Z', 'tBodyAcc-correlation()-Y,Z', 'tGravityAcc-mean()-X', 'tGravityAcc-mean()-Y', 'tGravityAcc-mean()-Z', 'tGravityAcc-std()-X', 'tGravityAcc-std()-Y', 'tGravityAcc-std()-Z', 'tGravityAcc-mad()-X', 'tGravityAcc-mad()-Y', 'tGravityAcc-mad()-Z', 'tGravityAcc-max()-X', 'tGravityAcc-max()-Y', 'tGravityAcc-max()-Z', 'tGravityAcc-min()-X', 'tGravityAcc-min()-Y', 'tGravityAcc-min()-Z', 'tGravityAcc-sma()', 'tGravityAcc-energy()-X', 'tGravityAcc-energy()-Y', 'tGravityAcc-energy()-Z', 'tGravityAcc-iqr()-X', 'tGravityAcc-iqr()-Y', 'tGravityAcc-iqr()-Z', 'tGravityAcc-entropy()-X', 'tGravityAcc-entropy()-Y', 'tGravityAcc-entropy()-Z', 'tGravityAcc-arCoeff()-X,1', 'tGravityAcc-arCoeff()-X,2', 'tGravityAcc-arCoeff()-X,3', 'tGravityAcc-arCoeff()-X,4', 'tGravityAcc-arCoeff()-Y,1', 'tGravityAcc-arCoeff()-Y,2', 'tGravityAcc-arCoeff()-Y,3', 'tGravityAcc-arCoeff()-Y,4', 'tGravityAcc-arCoeff()-Z,1', 'tGravityAcc-arCoeff()-Z,2', 'tGravityAcc-arCoeff()-Z,3', 'tGravityAcc-arCoeff()-Z,4', 'tGravityAcc-correlation()-X,Y', 'tGravityAcc-correlation()-X,Z', 'tGravityAcc-correlation()-Y,Z', 'tBodyAccJerk-mean()-X', 'tBodyAccJerk-mean()-Y', 'tBodyAccJerk-mean()-Z', 'tBodyAccJerk-std()-X', 'tBodyAccJerk-std()-Y', 'tBodyAccJerk-std()-Z', 'tBodyAccJerk-mad()-X', 'tBodyAccJerk-mad()-Y', 'tBodyAccJerk-mad()-Z', 'tBodyAccJerk-max()-X', 'tBodyAccJerk-max()-Y', 'tBodyAccJerk-max()-Z', 'tBodyAccJerk-min()-X', 'tBodyAccJerk-min()-Y', 'tBodyAccJerk-min()-Z', 'tBodyAccJerk-sma()', 'tBodyAccJerk-energy()-X', 'tBodyAccJerk-energy()-Y', 'tBodyAccJerk-energy()-Z', 'tBodyAccJerk-iqr()-X', 'tBodyAccJerk-iqr()-Y', 'tBodyAccJerk-iqr()-Z', 'tBodyAccJerk-entropy()-X', 'tBodyAccJerk-entropy()-Y', 'tBodyAccJerk-entropy()-Z', 'tBodyAccJerk-arCoeff()-X,1', 'tBodyAccJerk-arCoeff()-X,2', 'tBodyAccJerk-arCoeff()-X,3', 'tBodyAccJerk-arCoeff()-X,4', 'tBodyAccJerk-arCoeff()-Y,1', 'tBodyAccJerk-arCoeff()-Y,2', 'tBodyAccJerk-arCoeff()-Y,3', 'tBodyAccJerk-arCoeff()-Y,4', 'tBodyAccJerk-arCoeff()-Z,1', 'tBodyAccJerk-arCoeff()-Z,2', 'tBodyAccJerk-arCoeff()-Z,3', 'tBodyAccJerk-arCoeff()-Z,4', 'tBodyAccJerk-correlation()-X,Y', 'tBodyAccJerk-correlation()-X,Z', 'tBodyAccJerk-correlation()-Y,Z', 'tBodyGyro-mean()-X', 'tBodyGyro-mean()-Y', 'tBodyGyro-mean()-Z', 'tBodyGyro-std()-X', 'tBodyGyro-std()-Y', 'tBodyGyro-std()-Z', 'tBodyGyro-mad()-X', 'tBodyGyro-mad()-Y', 'tBodyGyro-mad()-Z', 'tBodyGyro-max()-X', 'tBodyGyro-max()-Y', 'tBodyGyro-max()-Z', 'tBodyGyro-min()-X', 'tBodyGyro-min()-Y', 'tBodyGyro-min()-Z', 'tBodyGyro-sma()', 'tBodyGyro-energy()-X', 'tBodyGyro-energy()-Y', 'tBodyGyro-energy()-Z', 'tBodyGyro-iqr()-X', 'tBodyGyro-iqr()-Y', 'tBodyGyro-iqr()-Z', 'tBodyGyro-entropy()-X', 'tBodyGyro-entropy()-Y', 'tBodyGyro-entropy()-Z', 'tBodyGyro-arCoeff()-X,1', 'tBodyGyro-arCoeff()-X,2', 'tBodyGyro-arCoeff()-X,3', 'tBodyGyro-arCoeff()-X,4', 'tBodyGyro-arCoeff()-Y,1', 'tBodyGyro-arCoeff()-Y,2', 'tBodyGyro-arCoeff()-Y,3', 'tBodyGyro-arCoeff()-Y,4', 'tBodyGyro-arCoeff()-Z,1', 'tBodyGyro-arCoeff()-Z,2', 'tBodyGyro-arCoeff()-Z,3', 'tBodyGyro-arCoeff()-Z,4', 'tBodyGyro-correlation()-X,Y', 'tBodyGyro-correlation()-X,Z', 'tBodyGyro-correlation()-Y,Z', 'tBodyGyroJerk-mean()-X', 'tBodyGyroJerk-mean()-Y', 'tBodyGyroJerk-mean()-Z', 'tBodyGyroJerk-std()-X', 'tBodyGyroJerk-std()-Y', 'tBodyGyroJerk-std()-Z', 'tBodyGyroJerk-mad()-X', 'tBodyGyroJerk-mad()-Y', 'tBodyGyroJerk-mad()-Z', 'tBodyGyroJerk-max()-X', 'tBodyGyroJerk-max()-Y', 'tBodyGyroJerk-max()-Z', 'tBodyGyroJerk-min()-X', 'tBodyGyroJerk-min()-Y', 'tBodyGyroJerk-min()-Z', 'tBodyGyroJerk-sma()', 'tBodyGyroJerk-energy()-X', 'tBodyGyroJerk-energy()-Y', 'tBodyGyroJerk-energy()-Z', 'tBodyGyroJerk-iqr()-X', 'tBodyGyroJerk-iqr()-Y', 'tBodyGyroJerk-iqr()-Z', 'tBodyGyroJerk-entropy()-X', 'tBodyGyroJerk-entropy()-Y', 'tBodyGyroJerk-entropy()-Z', 'tBodyGyroJerk-arCoeff()-X,1', 'tBodyGyroJerk-arCoeff()-X,2', 'tBodyGyroJerk-arCoeff()-X,3', 'tBodyGyroJerk-arCoeff()-X,4', 'tBodyGyroJerk-arCoeff()-Y,1', 'tBodyGyroJerk-arCoeff()-Y,2', 'tBodyGyroJerk-arCoeff()-Y,3', 'tBodyGyroJerk-arCoeff()-Y,4', 'tBodyGyroJerk-arCoeff()-Z,1', 'tBodyGyroJerk-arCoeff()-Z,2', 'tBodyGyroJerk-arCoeff()-Z,3', 'tBodyGyroJerk-arCoeff()-Z,4', 'tBodyGyroJerk-correlation()-X,Y', 'tBodyGyroJerk-correlation()-X,Z', 'tBodyGyroJerk-correlation()-Y,Z', 'tBodyAccMag-mean()', 'tBodyAccMag-std()', 'tBodyAccMag-mad()', 'tBodyAccMag-max()', 'tBodyAccMag-min()', 'tBodyAccMag-energy()', 'tBodyAccMag-iqr()', 'tBodyAccMag-entropy()', 'tBodyAccMag-arCoeff()1', 'tBodyAccMag-arCoeff()2', 'tBodyAccMag-arCoeff()3', 'tBodyAccMag-arCoeff()4', 'tBodyAccJerkMag-mean()', 'tBodyAccJerkMag-std()', 'tBodyAccJerkMag-mad()', 'tBodyAccJerkMag-max()', 'tBodyAccJerkMag-min()', 'tBodyAccJerkMag-energy()', 'tBodyAccJerkMag-iqr()', 'tBodyAccJerkMag-entropy()', 'tBodyAccJerkMag-arCoeff()1', 'tBodyAccJerkMag-arCoeff()2', 'tBodyAccJerkMag-arCoeff()3', 'tBodyAccJerkMag-arCoeff()4', 'tBodyGyroMag-mean()', 'tBodyGyroMag-std()', 'tBodyGyroMag-mad()', 'tBodyGyroMag-max()', 'tBodyGyroMag-min()', 'tBodyGyroMag-energy()', 'tBodyGyroMag-iqr()', 'tBodyGyroMag-entropy()', 'tBodyGyroMag-arCoeff()1', 'tBodyGyroMag-arCoeff()2', 'tBodyGyroMag-arCoeff()3', 'tBodyGyroMag-arCoeff()4', 'tBodyGyroJerkMag-mean()', 'tBodyGyroJerkMag-std()', 'tBodyGyroJerkMag-mad()', 'tBodyGyroJerkMag-max()', 'tBodyGyroJerkMag-min()', 'tBodyGyroJerkMag-energy()', 'tBodyGyroJerkMag-iqr()', 'tBodyGyroJerkMag-entropy()', 'tBodyGyroJerkMag-arCoeff()1', 'tBodyGyroJerkMag-arCoeff()2', 'tBodyGyroJerkMag-arCoeff()3', 'tBodyGyroJerkMag-arCoeff()4', 'fBodyAcc-std()-X', 'fBodyAcc-std()-Y', 'fBodyAcc-std()-Z', 'fBodyAcc-mad()-X', 'fBodyAcc-mad()-Y', 'fBodyAcc-mad()-Z', 'fBodyAcc-sma()', 'fBodyAcc-iqr()-X', 'fBodyAcc-iqr()-Y', 'fBodyAcc-iqr()-Z', 'fBodyAcc-entropy()-X', 'fBodyAcc-entropy()-Y', 'fBodyAcc-entropy()-Z', 'fBodyAcc-maxInds-X', 'fBodyAcc-maxInds-Y', 'fBodyAcc-maxInds-Z', 'fBodyAcc-meanFreq()-X', 'fBodyAcc-meanFreq()-Y', 'fBodyAcc-meanFreq()-Z', 'fBodyAcc-skewness()-X', 'fBodyAcc-kurtosis()-X', 'fBodyAcc-skewness()-Y', 'fBodyAcc-kurtosis()-Y', 'fBodyAcc-skewness()-Z', 'fBodyAcc-kurtosis()-Z', 'fBodyAcc-bandsEnergy()-1,8', 'fBodyAcc-bandsEnergy()-9,16', 'fBodyAcc-bandsEnergy()-17,24', 'fBodyAcc-bandsEnergy()-25,32', 'fBodyAcc-bandsEnergy()-33,40', 'fBodyAcc-bandsEnergy()-41,48', 'fBodyAcc-bandsEnergy()-49,56', 'fBodyAcc-bandsEnergy()-57,64', 'fBodyAcc-bandsEnergy()-1,16', 'fBodyAcc-bandsEnergy()-17,32', 'fBodyAcc-bandsEnergy()-33,48', 'fBodyAcc-bandsEnergy()-49,64', 'fBodyAcc-bandsEnergy()-1,24', 'fBodyAcc-bandsEnergy()-25,48', 'fBodyAcc-bandsEnergy()-1,8.1', 'fBodyAcc-bandsEnergy()-9,16.1', 'fBodyAcc-bandsEnergy()-17,24.1', 'fBodyAcc-bandsEnergy()-25,32.1', 'fBodyAcc-bandsEnergy()-33,40.1', 'fBodyAcc-bandsEnergy()-41,48.1', 'fBodyAcc-bandsEnergy()-49,56.1', 'fBodyAcc-bandsEnergy()-57,64.1', 'fBodyAcc-bandsEnergy()-1,16.1', 'fBodyAcc-bandsEnergy()-17,32.1', 'fBodyAcc-bandsEnergy()-33,48.1', 'fBodyAcc-bandsEnergy()-49,64.1', 'fBodyAcc-bandsEnergy()-1,24.1', 'fBodyAcc-bandsEnergy()-25,48.1', 'fBodyAcc-bandsEnergy()-1,8.2', 'fBodyAcc-bandsEnergy()-9,16.2', 'fBodyAcc-bandsEnergy()-17,24.2', 'fBodyAcc-bandsEnergy()-25,32.2', 'fBodyAcc-bandsEnergy()-33,40.2', 'fBodyAcc-bandsEnergy()-41,48.2', 'fBodyAcc-bandsEnergy()-49,56.2', 'fBodyAcc-bandsEnergy()-57,64.2', 'fBodyAcc-bandsEnergy()-1,16.2', 'fBodyAcc-bandsEnergy()-17,32.2', 'fBodyAcc-bandsEnergy()-33,48.2', 'fBodyAcc-bandsEnergy()-49,64.2', 'fBodyAcc-bandsEnergy()-1,24.2', 'fBodyAcc-bandsEnergy()-25,48.2', 'fBodyAccJerk-std()-X', 'fBodyAccJerk-std()-Y', 'fBodyAccJerk-std()-Z', 'fBodyAccJerk-mad()-X', 'fBodyAccJerk-mad()-Y', 'fBodyAccJerk-mad()-Z', 'fBodyAccJerk-sma()', 'fBodyAccJerk-iqr()-X', 'fBodyAccJerk-iqr()-Y', 'fBodyAccJerk-iqr()-Z', 'fBodyAccJerk-entropy()-X', 'fBodyAccJerk-entropy()-Y', 'fBodyAccJerk-entropy()-Z', 'fBodyAccJerk-maxInds-X', 'fBodyAccJerk-maxInds-Y', 'fBodyAccJerk-maxInds-Z', 'fBodyAccJerk-meanFreq()-X', 'fBodyAccJerk-meanFreq()-Y', 'fBodyAccJerk-meanFreq()-Z', 'fBodyAccJerk-skewness()-X', 'fBodyAccJerk-kurtosis()-X', 'fBodyAccJerk-skewness()-Y', 'fBodyAccJerk-kurtosis()-Y', 'fBodyAccJerk-skewness()-Z', 'fBodyAccJerk-kurtosis()-Z', 'fBodyAccJerk-bandsEnergy()-1,8', 'fBodyAccJerk-bandsEnergy()-9,16', 'fBodyAccJerk-bandsEnergy()-17,24', 'fBodyAccJerk-bandsEnergy()-25,32', 'fBodyAccJerk-bandsEnergy()-33,40', 'fBodyAccJerk-bandsEnergy()-41,48', 'fBodyAccJerk-bandsEnergy()-49,56', 'fBodyAccJerk-bandsEnergy()-57,64', 'fBodyAccJerk-bandsEnergy()-1,16', 'fBodyAccJerk-bandsEnergy()-17,32', 'fBodyAccJerk-bandsEnergy()-33,48', 'fBodyAccJerk-bandsEnergy()-49,64', 'fBodyAccJerk-bandsEnergy()-1,24', 'fBodyAccJerk-bandsEnergy()-25,48', 'fBodyAccJerk-bandsEnergy()-1,8.1', 'fBodyAccJerk-bandsEnergy()-9,16.1', 'fBodyAccJerk-bandsEnergy()-17,24.1', 'fBodyAccJerk-bandsEnergy()-25,32.1', 'fBodyAccJerk-bandsEnergy()-33,40.1', 'fBodyAccJerk-bandsEnergy()-41,48.1', 'fBodyAccJerk-bandsEnergy()-49,56.1', 'fBodyAccJerk-bandsEnergy()-57,64.1', 'fBodyAccJerk-bandsEnergy()-1,16.1', 'fBodyAccJerk-bandsEnergy()-17,32.1', 'fBodyAccJerk-bandsEnergy()-33,48.1', 'fBodyAccJerk-bandsEnergy()-49,64.1', 'fBodyAccJerk-bandsEnergy()-1,24.1', 'fBodyAccJerk-bandsEnergy()-25,48.1', 'fBodyAccJerk-bandsEnergy()-1,8.2', 'fBodyAccJerk-bandsEnergy()-9,16.2', 'fBodyAccJerk-bandsEnergy()-17,24.2', 'fBodyAccJerk-bandsEnergy()-25,32.2', 'fBodyAccJerk-bandsEnergy()-33,40.2', 'fBodyAccJerk-bandsEnergy()-41,48.2', 'fBodyAccJerk-bandsEnergy()-49,56.2', 'fBodyAccJerk-bandsEnergy()-57,64.2', 'fBodyAccJerk-bandsEnergy()-1,16.2', 'fBodyAccJerk-bandsEnergy()-17,32.2', 'fBodyAccJerk-bandsEnergy()-33,48.2', 'fBodyAccJerk-bandsEnergy()-49,64.2', 'fBodyAccJerk-bandsEnergy()-1,24.2', 'fBodyAccJerk-bandsEnergy()-25,48.2', 'fBodyGyro-std()-X', 'fBodyGyro-std()-Y', 'fBodyGyro-std()-Z', 'fBodyGyro-mad()-X', 'fBodyGyro-mad()-Y', 'fBodyGyro-mad()-Z', 'fBodyGyro-sma()', 'fBodyGyro-iqr()-X', 'fBodyGyro-iqr()-Y', 'fBodyGyro-iqr()-Z', 'fBodyGyro-entropy()-X', 'fBodyGyro-entropy()-Y', 'fBodyGyro-entropy()-Z', 'fBodyGyro-maxInds-X', 'fBodyGyro-maxInds-Y', 'fBodyGyro-maxInds-Z', 'fBodyGyro-meanFreq()-X', 'fBodyGyro-meanFreq()-Y', 'fBodyGyro-meanFreq()-Z', 'fBodyGyro-skewness()-X', 'fBodyGyro-kurtosis()-X', 'fBodyGyro-skewness()-Y', 'fBodyGyro-kurtosis()-Y', 'fBodyGyro-skewness()-Z', 'fBodyGyro-kurtosis()-Z', 'fBodyGyro-bandsEnergy()-1,8', 'fBodyGyro-bandsEnergy()-9,16', 'fBodyGyro-bandsEnergy()-17,24', 'fBodyGyro-bandsEnergy()-25,32', 'fBodyGyro-bandsEnergy()-33,40', 'fBodyGyro-bandsEnergy()-41,48', 'fBodyGyro-bandsEnergy()-49,56', 'fBodyGyro-bandsEnergy()-57,64', 'fBodyGyro-bandsEnergy()-1,16', 'fBodyGyro-bandsEnergy()-17,32', 'fBodyGyro-bandsEnergy()-33,48', 'fBodyGyro-bandsEnergy()-49,64', 'fBodyGyro-bandsEnergy()-1,24', 'fBodyGyro-bandsEnergy()-25,48', 'fBodyGyro-bandsEnergy()-1,8.1', 'fBodyGyro-bandsEnergy()-9,16.1', 'fBodyGyro-bandsEnergy()-17,24.1', 'fBodyGyro-bandsEnergy()-25,32.1', 'fBodyGyro-bandsEnergy()-33,40.1', 'fBodyGyro-bandsEnergy()-41,48.1', 'fBodyGyro-bandsEnergy()-49,56.1', 'fBodyGyro-bandsEnergy()-57,64.1', 'fBodyGyro-bandsEnergy()-1,16.1', 'fBodyGyro-bandsEnergy()-17,32.1', 'fBodyGyro-bandsEnergy()-33,48.1', 'fBodyGyro-bandsEnergy()-49,64.1', 'fBodyGyro-bandsEnergy()-1,24.1', 'fBodyGyro-bandsEnergy()-25,48.1', 'fBodyGyro-bandsEnergy()-1,8.2', 'fBodyGyro-bandsEnergy()-9,16.2', 'fBodyGyro-bandsEnergy()-17,24.2', 'fBodyGyro-bandsEnergy()-25,32.2', 'fBodyGyro-bandsEnergy()-33,40.2', 'fBodyGyro-bandsEnergy()-41,48.2', 'fBodyGyro-bandsEnergy()-49,56.2', 'fBodyGyro-bandsEnergy()-57,64.2', 'fBodyGyro-bandsEnergy()-1,16.2', 'fBodyGyro-bandsEnergy()-17,32.2', 'fBodyGyro-bandsEnergy()-33,48.2', 'fBodyGyro-bandsEnergy()-49,64.2', 'fBodyGyro-bandsEnergy()-1,24.2', 'fBodyGyro-bandsEnergy()-25,48.2', 'fBodyAccMag-std()', 'fBodyAccMag-mad()', 'fBodyAccMag-iqr()', 'fBodyAccMag-entropy()', 'fBodyAccMag-maxInds', 'fBodyAccMag-meanFreq()', 'fBodyAccMag-skewness()', 'fBodyAccMag-kurtosis()', 'fBodyBodyAccJerkMag-std()', 'fBodyBodyAccJerkMag-mad()', 'fBodyBodyAccJerkMag-iqr()', 'fBodyBodyAccJerkMag-entropy()', 'fBodyBodyAccJerkMag-maxInds', 'fBodyBodyAccJerkMag-meanFreq()', 'fBodyBodyAccJerkMag-skewness()', 'fBodyBodyAccJerkMag-kurtosis()', 'fBodyBodyGyroMag-std()', 'fBodyBodyGyroMag-mad()', 'fBodyBodyGyroMag-iqr()', 'fBodyBodyGyroMag-entropy()', 'fBodyBodyGyroMag-maxInds', 'fBodyBodyGyroMag-meanFreq()', 'fBodyBodyGyroMag-skewness()', 'fBodyBodyGyroMag-kurtosis()', 'fBodyBodyGyroJerkMag-std()', 'fBodyBodyGyroJerkMag-mad()', 'fBodyBodyGyroJerkMag-iqr()', 'fBodyBodyGyroJerkMag-entropy()', 'fBodyBodyGyroJerkMag-maxInds', 'fBodyBodyGyroJerkMag-meanFreq()', 'fBodyBodyGyroJerkMag-skewness()', 'fBodyBodyGyroJerkMag-kurtosis()', 'angle(tBodyAccMean,gravity)', 'angle(tBodyAccJerkMean),gravityMean)', 'angle(tBodyGyroMean,gravityMean)', 'angle(tBodyGyroJerkMean,gravityMean)', 'angle(X,gravityMean)', 'angle(Y,gravityMean)', 'angle(Z,gravityMean)', 'subject', 'Activity']

In [132]:
cleaned_df = pd.concat([df_cleaned, df[['Activity', 'subject']]], axis=1)

cleaned_df.to_csv(rf'../dataset/full.v3_{now}.csv', index=False)