In [165]:
import pandas as pd # Data structure for CSV
import re # Regular Expressions
from sklearn.feature_selection import VarianceThreshold

df = pd.read_csv('../dataset/full.csv')
prev_df = pd.read_csv('../dataset/full.csv')
df_columns = df.columns.tolist()
df_cleaned = pd.DataFrame()
prev_df_columns = []

df.head()

,tBodyAcc-mean()-X,tBodyAcc-mean()-Y,tBodyAcc-mean()-Z,tBodyAcc-std()-X,tBodyAcc-std()-Y,tBodyAcc-std()-Z,tBodyAcc-mad()-X,tBodyAcc-mad()-Y,tBodyAcc-mad()-Z,tBodyAcc-max()-X,...,fBodyBodyGyroJerkMag-kurtosis(),"angle(tBodyAccMean,gravity)","angle(tBodyAccJerkMean),gravityMean)","angle(tBodyGyroMean,gravityMean)","angle(tBodyGyroJerkMean,gravityMean)","angle(X,gravityMean)","angle(Y,gravityMean)","angle(Z,gravityMean)",subject,Activity
0,0.288585,-0.020294,-0.132905,-0.995279,-0.983111,-0.913526,-0.995112,-0.983185,-0.923527,-0.934724,...,-0.710304,-0.112754,0.030400,-0.464761,-0.018446,-0.841247,0.179941,-0.058627,1,STANDING
1,0.278419,-0.016411,-0.123520,-0.998245,-0.975300,-0.960322,-0.998807,-0.974914,-0.957686,-0.943068,...,-0.861499,0.053477,-0.007435,-0.732626,0.703511,-0.844788,0.180289,-0.054317,1,STANDING
2,0.279653,-0.019467,-0.113462,-0.995380,-0.967187,-0.978944,-0.996520,-0.963668,-0.977469,-0.938692,...,-0.760104,-0.118559,0.177899,0.100699,0.808529,-0.848933,0.180637,-0.049118,1,STANDING
3,0.279174,-0.026201,-0.123283,-0.996091,-0.983403,-0.990675,-0.997099,-0.982750,-0.989302,-0.938692,...,-0.482845,-0.036788,-0.012892,0.640011,-0.485366,-0.848649,0.181935,-0.047663,1,STANDING
4,0.276629,-0.016570,-0.115362,-0.998139,-0.980817,-0.990482,-0.998321,-0.979672,-0.990441,-0.942469,...,-0.699205,0.123320,0.122542,0.693578,-0.615971,-0.847865,0.185151,-0.043892,1,STANDING

In [166]:
def compare_df():    
    if df_cleaned.empty:
        return
    df_cleaned_columns = df_cleaned.columns.tolist()
    prev_df_columns = prev_df.columns.tolist()

    diff_list_total = list(set(df_columns) - set(df_cleaned_columns))
    diff_list = list(list(set(prev_df_columns) - set(df_cleaned_columns)))

    df_columns_count = len(df_columns)
    df_cleaned_columns_count = len(df_cleaned_columns)
    prev_df_columns_count = len(prev_df_columns)

    total_removed_features = df_columns_count - df_cleaned_columns_count
    this_step_removed_features = prev_df_columns_count - df_cleaned_columns_count

    print("Features excluded (in total):")
    print(diff_list_total)
    print('='*50)
    print("Features excluded (this step):")
    print(diff_list)
    print('='*50)
    print("Removed total: " + str(df_columns_count) + " ---> " + str(df_cleaned_columns_count) + " features")
    print("Total feature removal count: " + str(total_removed_features))
    print('='*50)
    print("Removed this step: " + str(prev_df_columns_count) + " ---> " + str(df_cleaned_columns_count) + " features")
    print("Feature removal this step count: " + str(this_step_removed_features))

# Feature extraction/selection

First, we remove features that contain duplicate data to another.

In [167]:
df_cleaned = df.T.drop_duplicates(keep='first').T

df_cleaned.head()

,tBodyAcc-mean()-X,tBodyAcc-mean()-Y,tBodyAcc-mean()-Z,tBodyAcc-std()-X,tBodyAcc-std()-Y,tBodyAcc-std()-Z,tBodyAcc-mad()-X,tBodyAcc-mad()-Y,tBodyAcc-mad()-Z,tBodyAcc-max()-X,...,fBodyBodyGyroJerkMag-kurtosis(),"angle(tBodyAccMean,gravity)","angle(tBodyAccJerkMean),gravityMean)","angle(tBodyGyroMean,gravityMean)","angle(tBodyGyroJerkMean,gravityMean)","angle(X,gravityMean)","angle(Y,gravityMean)","angle(Z,gravityMean)",subject,Activity
0,0.288585,-0.020294,-0.132905,-0.995279,-0.983111,-0.913526,-0.995112,-0.983185,-0.923527,-0.934724,...,-0.710304,-0.112754,0.0304,-0.464761,-0.018446,-0.841247,0.179941,-0.058627,1,STANDING
1,0.278419,-0.016411,-0.12352,-0.998245,-0.9753,-0.960322,-0.998807,-0.974914,-0.957686,-0.943068,...,-0.861499,0.053477,-0.007435,-0.732626,0.703511,-0.844788,0.180289,-0.054317,1,STANDING
2,0.279653,-0.019467,-0.113462,-0.99538,-0.967187,-0.978944,-0.99652,-0.963668,-0.977469,-0.938692,...,-0.760104,-0.118559,0.177899,0.100699,0.808529,-0.848933,0.180637,-0.049118,1,STANDING
3,0.279174,-0.026201,-0.123283,-0.996091,-0.983403,-0.990675,-0.997099,-0.98275,-0.989302,-0.938692,...,-0.482845,-0.036788,-0.012892,0.640011,-0.485366,-0.848649,0.181935,-0.047663,1,STANDING
4,0.276629,-0.01657,-0.115362,-0.998139,-0.980817,-0.990482,-0.998321,-0.979672,-0.990441,-0.942469,...,-0.699205,0.12332,0.122542,0.693578,-0.615971,-0.847865,0.185151,-0.043892,1,STANDING

In [168]:
compare_df()
prev_df = df_cleaned

Features excluded (in total):
['tBodyAccMag-sma()', 'tGravityAccMag-energy()', 'tGravityAccMag-mean()', 'fBodyBodyGyroMag-sma()', 'tGravityAccMag-mad()', 'tBodyAccJerkMag-sma()', 'tGravityAccMag-iqr()', 'tGravityAccMag-std()', 'fBodyBodyGyroJerkMag-sma()', 'tGravityAccMag-entropy()', 'tGravityAccMag-max()', 'tBodyGyroJerkMag-sma()', 'tGravityAccMag-min()', 'tGravityAccMag-arCoeff()3', 'fBodyAccMag-sma()', 'tBodyGyroMag-sma()', 'fBodyBodyAccJerkMag-sma()', 'tGravityAccMag-arCoeff()1', 'tGravityAccMag-arCoeff()2', 'tGravityAccMag-arCoeff()4', 'tGravityAccMag-sma()']
==================================================
Features excluded (this step):
['tBodyAccMag-sma()', 'tGravityAccMag-energy()', 'tGravityAccMag-mean()', 'fBodyBodyGyroMag-sma()', 'tGravityAccMag-mad()', 'tBodyAccJerkMag-sma()', 'tGravityAccMag-iqr()', 'tGravityAccMag-std()', 'fBodyBodyGyroJerkMag-sma()', 'tGravityAccMag-entropy()', 'tGravityAccMag-max()', 'tBodyGyroJerkMag-sma()', 'tGravityAccMag-min()', 'tGravityAccMag-arCoeff()3', 'fBodyAccMag-sma()', 'tBodyGyroMag-sma()', 'fBodyBodyAccJerkMag-sma()', 'tGravityAccMag-arCoeff()1', 'tGravityAccMag-arCoeff()2', 'tGravityAccMag-arCoeff()4', 'tGravityAccMag-sma()']
==================================================
Removed total: 563 ---> 542 features
Total feature removal count: 21
==================================================
Removed this step: 563 ---> 542 features
Feature removal this step count: 21

563 ---> 542 features

### Then, we consider what type of feature:
In the dataset, we've got two types of recorded data:
- t-* features: Raw time-series signals recorded at 50hz
- f-* features: Signals transformed using Fast Fourier Transform

There are mathematical functions that have been applied to numerous features, and in some cases the "t" and "p" version of these functions yield no new information.

## Gemini breakdown because my dumbass dont know shit about physics:

### What you can safely remove:
f*-mean():
This function calculates the plain arithmetic mean of the Fourier amplitudes across all frequency bins. For primary acceleration, this is mathematically tied to the baseline time-domain average (tBodyAcc-mean()) or overall signal power. Dropping these across the board will cause almost zero loss in model accuracy because the time-domain equivalent (t) already captures the signal's overall magnitude

f*.max() + f*.min():
Why f is redundant/invalid: In the time domain, tBodyAcc-max()-X tells you the maximum G-force impulse experienced during a movement step. In the frequency domain, fBodyAcc-max()-X simply tells you the amplitude of the single strongest frequency peak. While peak frequency amplitude is informative, peak frequency intensity is already captured far more comprehensively by fBodyAcc-maxFreqInd (index of peak frequency) or fBodyAcc-energy()

f*.std() + f*.iqr() + f*.energy():
Why f is redundant/invalid: Thanks to Parseval’s Theorem, the total energy (variance) of a signal in the time domain is mathematically equal to the total energy of the signal in the frequency domain. Calculating dispersion statistics like std() or iqr() on the time signal tBodyAcc directly measures movement volatility. Doing the exact same calculation on the FFT bins (fBodyAcc-std()) simply measures how spread out the frequency amplitudes are, which strongly co-varies with time-domain variance.

Source for Parseval's Theorem and its valid application in sensory data feature extraction: 
 10.1109/access.2020.2996576

In [169]:
total_features = df_cleaned.columns.tolist()

# Let's remove all f*-mean():
regex = r"^f.*-mean\(\)"
features_to_remove = [i for i in total_features if re.search(regex, i)]
df_cleaned = df_cleaned.drop(columns=features_to_remove)

# Remove all f*-max():
regex = r"^f.*-max\(\)"
features_to_remove = []
features_to_remove = [i for i in total_features if re.search(regex, i)]
df_cleaned = df_cleaned.drop(columns=features_to_remove)

# Remove all f*-min():
regex = r"^f.*-min\(\)"
features_to_remove = []
features_to_remove = [i for i in total_features if re.search(regex, i)]
df_cleaned = df_cleaned.drop(columns=features_to_remove)

df_cleaned.head()

,tBodyAcc-mean()-X,tBodyAcc-mean()-Y,tBodyAcc-mean()-Z,tBodyAcc-std()-X,tBodyAcc-std()-Y,tBodyAcc-std()-Z,tBodyAcc-mad()-X,tBodyAcc-mad()-Y,tBodyAcc-mad()-Z,tBodyAcc-max()-X,...,fBodyBodyGyroJerkMag-kurtosis(),"angle(tBodyAccMean,gravity)","angle(tBodyAccJerkMean),gravityMean)","angle(tBodyGyroMean,gravityMean)","angle(tBodyGyroJerkMean,gravityMean)","angle(X,gravityMean)","angle(Y,gravityMean)","angle(Z,gravityMean)",subject,Activity
0,0.288585,-0.020294,-0.132905,-0.995279,-0.983111,-0.913526,-0.995112,-0.983185,-0.923527,-0.934724,...,-0.710304,-0.112754,0.0304,-0.464761,-0.018446,-0.841247,0.179941,-0.058627,1,STANDING
1,0.278419,-0.016411,-0.12352,-0.998245,-0.9753,-0.960322,-0.998807,-0.974914,-0.957686,-0.943068,...,-0.861499,0.053477,-0.007435,-0.732626,0.703511,-0.844788,0.180289,-0.054317,1,STANDING
2,0.279653,-0.019467,-0.113462,-0.99538,-0.967187,-0.978944,-0.99652,-0.963668,-0.977469,-0.938692,...,-0.760104,-0.118559,0.177899,0.100699,0.808529,-0.848933,0.180637,-0.049118,1,STANDING
3,0.279174,-0.026201,-0.123283,-0.996091,-0.983403,-0.990675,-0.997099,-0.98275,-0.989302,-0.938692,...,-0.482845,-0.036788,-0.012892,0.640011,-0.485366,-0.848649,0.181935,-0.047663,1,STANDING
4,0.276629,-0.01657,-0.115362,-0.998139,-0.980817,-0.990482,-0.998321,-0.979672,-0.990441,-0.942469,...,-0.699205,0.12332,0.122542,0.693578,-0.615971,-0.847865,0.185151,-0.043892,1,STANDING

In [170]:
compare_df()
prev_df = df_cleaned

Features excluded (in total):
['fBodyAccJerk-max()-X', 'fBodyGyro-max()-Z', 'fBodyAccJerk-min()-X', 'tBodyAccMag-sma()', 'tGravityAccMag-energy()', 'fBodyAcc-min()-Y', 'fBodyBodyGyroJerkMag-mean()', 'tGravityAccMag-mean()', 'fBodyAccJerk-max()-Y', 'fBodyBodyGyroMag-sma()', 'fBodyGyro-max()-X', 'fBodyGyro-max()-Y', 'tGravityAccMag-mad()', 'fBodyAccJerk-mean()-Z', 'tBodyAccJerkMag-sma()', 'fBodyAcc-max()-Y', 'tGravityAccMag-iqr()', 'tGravityAccMag-std()', 'fBodyAcc-mean()-X', 'fBodyBodyAccJerkMag-mean()', 'fBodyBodyGyroJerkMag-sma()', 'fBodyBodyAccJerkMag-min()', 'fBodyAcc-min()-Z', 'fBodyAccJerk-mean()-Y', 'fBodyAccMag-mean()', 'tGravityAccMag-entropy()', 'fBodyAcc-mean()-Z', 'tGravityAccMag-max()', 'fBodyAcc-min()-X', 'fBodyGyro-mean()-Z', 'tBodyGyroJerkMag-sma()', 'fBodyBodyGyroMag-min()', 'fBodyBodyAccJerkMag-max()', 'fBodyGyro-mean()-X', 'tGravityAccMag-min()', 'fBodyBodyGyroJerkMag-min()', 'fBodyGyro-min()-X', 'fBodyAccJerk-max()-Z', 'fBodyGyro-min()-Z', 'fBodyBodyGyroMag-mean()', 'fBodyAcc-max()-Z', 'fBodyAcc-max()-X', 'tGravityAccMag-arCoeff()3', 'fBodyAccMag-min()', 'fBodyAccMag-sma()', 'tBodyGyroMag-sma()', 'fBodyBodyAccJerkMag-sma()', 'tGravityAccMag-arCoeff()1', 'tGravityAccMag-arCoeff()2', 'fBodyGyro-min()-Y', 'fBodyBodyGyroMag-max()', 'fBodyAcc-mean()-Y', 'fBodyAccMag-max()', 'fBodyAccJerk-mean()-X', 'fBodyBodyGyroJerkMag-max()', 'fBodyAccJerk-min()-Y', 'fBodyAccJerk-min()-Z', 'fBodyGyro-mean()-Y', 'tGravityAccMag-arCoeff()4', 'tGravityAccMag-sma()']
==================================================
Features excluded (this step):
['fBodyAccJerk-max()-X', 'fBodyGyro-max()-Z', 'fBodyAccJerk-min()-X', 'fBodyBodyGyroJerkMag-mean()', 'fBodyAcc-min()-Y', 'fBodyAccJerk-max()-Y', 'fBodyGyro-max()-X', 'fBodyGyro-max()-Y', 'fBodyAccJerk-mean()-Z', 'fBodyAcc-max()-Y', 'fBodyAcc-mean()-X', 'fBodyBodyAccJerkMag-mean()', 'fBodyAcc-mean()-Z', 'fBodyBodyAccJerkMag-min()', 'fBodyAcc-min()-Z', 'fBodyAccJerk-mean()-Y', 'fBodyAccMag-mean()', 'fBodyAcc-min()-X', 'fBodyGyro-mean()-Z', 'fBodyBodyGyroMag-min()', 'fBodyBodyAccJerkMag-max()', 'fBodyGyro-mean()-X', 'fBodyBodyGyroJerkMag-min()', 'fBodyGyro-min()-X', 'fBodyAccJerk-max()-Z', 'fBodyGyro-min()-Z', 'fBodyBodyGyroMag-mean()', 'fBodyAcc-max()-Z', 'fBodyAcc-max()-X', 'fBodyAccMag-min()', 'fBodyGyro-min()-Y', 'fBodyBodyGyroMag-max()', 'fBodyAcc-mean()-Y', 'fBodyAccMag-max()', 'fBodyAccJerk-mean()-X', 'fBodyBodyGyroJerkMag-max()', 'fBodyAccJerk-min()-Y', 'fBodyAccJerk-min()-Z', 'fBodyGyro-mean()-Y']
==================================================
Removed total: 563 ---> 503 features
Total feature removal count: 60
==================================================
Removed this step: 542 ---> 503 features
Feature removal this step count: 39

542 ---> 503 features

In [171]:
# Remove all f*"-energy" (excluding bandsEnergy)
regex = r"^f.*-energy\(\)"
features_to_remove = []
features_to_remove = [i for i in total_features if re.search(regex, i)]
df_cleaned = df_cleaned.drop(columns=features_to_remove)
df_cleaned.head()

,tBodyAcc-mean()-X,tBodyAcc-mean()-Y,tBodyAcc-mean()-Z,tBodyAcc-std()-X,tBodyAcc-std()-Y,tBodyAcc-std()-Z,tBodyAcc-mad()-X,tBodyAcc-mad()-Y,tBodyAcc-mad()-Z,tBodyAcc-max()-X,...,fBodyBodyGyroJerkMag-kurtosis(),"angle(tBodyAccMean,gravity)","angle(tBodyAccJerkMean),gravityMean)","angle(tBodyGyroMean,gravityMean)","angle(tBodyGyroJerkMean,gravityMean)","angle(X,gravityMean)","angle(Y,gravityMean)","angle(Z,gravityMean)",subject,Activity
0,0.288585,-0.020294,-0.132905,-0.995279,-0.983111,-0.913526,-0.995112,-0.983185,-0.923527,-0.934724,...,-0.710304,-0.112754,0.0304,-0.464761,-0.018446,-0.841247,0.179941,-0.058627,1,STANDING
1,0.278419,-0.016411,-0.12352,-0.998245,-0.9753,-0.960322,-0.998807,-0.974914,-0.957686,-0.943068,...,-0.861499,0.053477,-0.007435,-0.732626,0.703511,-0.844788,0.180289,-0.054317,1,STANDING
2,0.279653,-0.019467,-0.113462,-0.99538,-0.967187,-0.978944,-0.99652,-0.963668,-0.977469,-0.938692,...,-0.760104,-0.118559,0.177899,0.100699,0.808529,-0.848933,0.180637,-0.049118,1,STANDING
3,0.279174,-0.026201,-0.123283,-0.996091,-0.983403,-0.990675,-0.997099,-0.98275,-0.989302,-0.938692,...,-0.482845,-0.036788,-0.012892,0.640011,-0.485366,-0.848649,0.181935,-0.047663,1,STANDING
4,0.276629,-0.01657,-0.115362,-0.998139,-0.980817,-0.990482,-0.998321,-0.979672,-0.990441,-0.942469,...,-0.699205,0.12332,0.122542,0.693578,-0.615971,-0.847865,0.185151,-0.043892,1,STANDING

In [172]:
compare_df()
prev_df = df_cleaned

Features excluded (in total):
['fBodyAccJerk-max()-X', 'fBodyGyro-max()-Z', 'fBodyAccJerk-min()-X', 'tBodyAccMag-sma()', 'tGravityAccMag-energy()', 'fBodyAcc-min()-Y', 'fBodyBodyAccJerkMag-energy()', 'tGravityAccMag-mean()', 'fBodyBodyGyroJerkMag-mean()', 'fBodyAccJerk-max()-Y', 'fBodyBodyGyroMag-sma()', 'fBodyGyro-max()-X', 'fBodyGyro-max()-Y', 'tGravityAccMag-mad()', 'fBodyAccJerk-mean()-Z', 'tBodyAccJerkMag-sma()', 'fBodyAcc-max()-Y', 'tGravityAccMag-iqr()', 'tGravityAccMag-std()', 'fBodyGyro-energy()-X', 'fBodyAcc-mean()-X', 'fBodyBodyAccJerkMag-mean()', 'fBodyBodyGyroJerkMag-sma()', 'fBodyBodyAccJerkMag-min()', 'fBodyAcc-min()-Z', 'fBodyAccJerk-mean()-Y', 'fBodyAccMag-mean()', 'tGravityAccMag-entropy()', 'fBodyAcc-mean()-Z', 'tGravityAccMag-max()', 'fBodyAcc-energy()-Z', 'fBodyAccJerk-energy()-Z', 'fBodyAcc-min()-X', 'fBodyGyro-mean()-Z', 'tBodyGyroJerkMag-sma()', 'fBodyAcc-energy()-Y', 'fBodyBodyGyroMag-min()', 'fBodyBodyAccJerkMag-max()', 'fBodyGyro-mean()-X', 'tGravityAccMag-min()', 'fBodyBodyGyroJerkMag-min()', 'fBodyGyro-min()-X', 'fBodyAccJerk-max()-Z', 'fBodyGyro-min()-Z', 'fBodyBodyGyroMag-mean()', 'fBodyAccMag-energy()', 'fBodyAcc-max()-Z', 'fBodyGyro-energy()-Y', 'fBodyAcc-energy()-X', 'fBodyBodyGyroJerkMag-energy()', 'fBodyAcc-max()-X', 'tGravityAccMag-arCoeff()3', 'fBodyAccJerk-energy()-Y', 'fBodyAccMag-min()', 'fBodyAccMag-sma()', 'tBodyGyroMag-sma()', 'fBodyGyro-energy()-Z', 'tGravityAccMag-arCoeff()1', 'fBodyBodyAccJerkMag-sma()', 'tGravityAccMag-arCoeff()2', 'fBodyGyro-min()-Y', 'fBodyBodyGyroMag-max()', 'fBodyAcc-mean()-Y', 'fBodyAccMag-max()', 'fBodyAccJerk-energy()-X', 'fBodyAccJerk-mean()-X', 'fBodyBodyGyroJerkMag-max()', 'fBodyAccJerk-min()-Y', 'fBodyAccJerk-min()-Z', 'fBodyGyro-mean()-Y', 'tGravityAccMag-arCoeff()4', 'fBodyBodyGyroMag-energy()', 'tGravityAccMag-sma()']
==================================================
Features excluded (this step):
['fBodyGyro-energy()-Z', 'fBodyBodyAccJerkMag-energy()', 'fBodyAcc-energy()-Z', 'fBodyAccJerk-energy()-Z', 'fBodyAccJerk-energy()-X', 'fBodyAccMag-energy()', 'fBodyGyro-energy()-Y', 'fBodyBodyGyroJerkMag-energy()', 'fBodyAcc-energy()-X', 'fBodyAcc-energy()-Y', 'fBodyGyro-energy()-X', 'fBodyBodyGyroMag-energy()', 'fBodyAccJerk-energy()-Y']
==================================================
Removed total: 563 ---> 490 features
Total feature removal count: 73
==================================================
Removed this step: 503 ---> 490 features
Feature removal this step count: 13

542 ---> 490 features

# Domain-Informed & Variance filtering

We are to drop features that have x % sharing of same values.

In [173]:
# We exclude 'subject' and 'Activity':
df_cleaned_no_categorical = df_cleaned.drop(columns=['Activity', 'subject'])

# We'll start easy: 1%.
selector = VarianceThreshold(threshold=0.01)
selector.fit(df_cleaned_no_categorical)

features_to_keep = df_cleaned_no_categorical.columns[selector.get_support()]

df_cleaned = df_cleaned[features_to_keep]

df_cleaned.head()

,tBodyAcc-std()-X,tBodyAcc-std()-Y,tBodyAcc-std()-Z,tBodyAcc-mad()-X,tBodyAcc-mad()-Y,tBodyAcc-mad()-Z,tBodyAcc-max()-X,tBodyAcc-max()-Y,tBodyAcc-max()-Z,tBodyAcc-min()-X,...,fBodyBodyGyroJerkMag-meanFreq(),fBodyBodyGyroJerkMag-skewness(),fBodyBodyGyroJerkMag-kurtosis(),"angle(tBodyAccMean,gravity)","angle(tBodyAccJerkMean),gravityMean)","angle(tBodyGyroMean,gravityMean)","angle(tBodyGyroJerkMean,gravityMean)","angle(X,gravityMean)","angle(Y,gravityMean)","angle(Z,gravityMean)"
0,-0.995279,-0.983111,-0.913526,-0.995112,-0.983185,-0.923527,-0.934724,-0.567378,-0.744413,0.852947,...,-0.074323,-0.298676,-0.710304,-0.112754,0.0304,-0.464761,-0.018446,-0.841247,0.179941,-0.058627
1,-0.998245,-0.9753,-0.960322,-0.998807,-0.974914,-0.957686,-0.943068,-0.557851,-0.818409,0.849308,...,0.158075,-0.595051,-0.861499,0.053477,-0.007435,-0.732626,0.703511,-0.844788,0.180289,-0.054317
2,-0.99538,-0.967187,-0.978944,-0.99652,-0.963668,-0.977469,-0.938692,-0.557851,-0.818409,0.843609,...,0.414503,-0.390748,-0.760104,-0.118559,0.177899,0.100699,0.808529,-0.848933,0.180637,-0.049118
3,-0.996091,-0.983403,-0.990675,-0.997099,-0.98275,-0.989302,-0.938692,-0.576159,-0.829711,0.843609,...,0.404573,-0.11729,-0.482845,-0.036788,-0.012892,0.640011,-0.485366,-0.848649,0.181935,-0.047663
4,-0.998139,-0.980817,-0.990482,-0.998321,-0.979672,-0.990441,-0.942469,-0.569174,-0.824705,0.849095,...,0.087753,-0.351471,-0.699205,0.12332,0.122542,0.693578,-0.615971,-0.847865,0.185151,-0.043892

In [174]:
compare_df()
prev_df = df_cleaned

Features excluded (in total):
['fBodyAccJerk-max()-X', 'fBodyAcc-bandsEnergy()-25,48.2', 'fBodyBodyAccJerkMag-energy()', 'tGravityAccMag-energy()', 'tGravityAcc-std()-X', 'tGravityAccMag-mad()', 'fBodyAccJerk-mean()-Z', 'fBodyAcc-mean()-X', 'fBodyBodyGyroJerkMag-sma()', 'fBodyBodyAccJerkMag-min()', 'fBodyAccJerk-energy()-Z', 'fBodyGyro-mean()-Z', 'fBodyGyro-bandsEnergy()-25,48', 'fBodyBodyGyroMag-min()', 'fBodyGyro-mean()-X', 'Activity', 'fBodyBodyGyroJerkMag-min()', 'fBodyGyro-min()-X', 'fBodyAccJerk-bandsEnergy()-57,64', 'fBodyAcc-bandsEnergy()-33,48.2', 'tGravityAccMag-arCoeff()2', 'fBodyGyro-min()-Y', 'fBodyAccMag-max()', 'subject', 'fBodyBodyGyroJerkMag-max()', 'fBodyAccJerk-min()-Y', 'fBodyAccJerk-min()-Z', 'fBodyGyro-bandsEnergy()-41,48.2', 'tGravityAcc-iqr()-X', 'fBodyGyro-bandsEnergy()-41,48', 'fBodyBodyGyroMag-energy()', 'fBodyAccJerk-min()-X', 'tBodyAccMag-sma()', 'fBodyBodyGyroJerkMag-mean()', 'fBodyAcc-bandsEnergy()-25,32.2', 'tGravityAccMag-std()', 'fBodyGyro-energy()-X', 'fBodyBodyAccJerkMag-mean()', 'fBodyAcc-mean()-Z', 'fBodyGyro-bandsEnergy()-25,32.1', 'fBodyGyro-bandsEnergy()-25,48.1', 'fBodyGyro-bandsEnergy()-33,40.2', 'fBodyGyro-bandsEnergy()-33,48.2', 'fBodyGyro-bandsEnergy()-33,40.1', 'fBodyAcc-energy()-Y', 'fBodyAccJerk-max()-Z', 'fBodyAcc-max()-Z', 'fBodyGyro-energy()-Y', 'fBodyAccJerk-bandsEnergy()-57,64.1', 'tGravityAccMag-arCoeff()3', 'fBodyAccMag-sma()', 'fBodyBodyAccJerkMag-sma()', 'fBodyAccJerk-mean()-X', 'fBodyGyro-mean()-Y', 'fBodyAccJerk-bandsEnergy()-57,64.2', 'fBodyGyro-max()-Z', 'fBodyAcc-min()-Y', 'tGravityAccMag-mean()', 'fBodyAccJerk-max()-Y', 'fBodyGyro-max()-X', 'fBodyGyro-max()-Y', 'tBodyAccJerkMag-sma()', 'fBodyAcc-max()-Y', 'fBodyAccJerk-mean()-Y', 'fBodyAccMag-mean()', 'tGravityAccMag-entropy()', 'tGravityAccMag-max()', 'fBodyAcc-energy()-Z', 'fBodyAcc-min()-X', 'tGravityAcc-mad()-Y', 'fBodyGyro-bandsEnergy()-57,64.1', 'fBodyAccJerk-bandsEnergy()-25,32.2', 'fBodyGyro-bandsEnergy()-49,64', 'tGravityAcc-std()-Y', 'tGravityAccMag-min()', 'fBodyGyro-bandsEnergy()-57,64.2', 'fBodyGyro-min()-Z', 'fBodyGyro-bandsEnergy()-49,64.2', 'fBodyGyro-bandsEnergy()-25,32.2', 'fBodyGyro-bandsEnergy()-25,48.2', 'fBodyAcc-energy()-X', 'tGravityAcc-iqr()-Y', 'fBodyGyro-bandsEnergy()-33,48.1', 'fBodyAccJerk-energy()-Y', 'tBodyGyroMag-sma()', 'fBodyGyro-energy()-Z', 'tGravityAccMag-arCoeff()1', 'fBodyGyro-bandsEnergy()-41,48.1', 'fBodyBodyGyroMag-max()', 'fBodyAccJerk-energy()-X', 'tBodyAcc-mean()-Z', 'fBodyAccJerk-bandsEnergy()-33,40.2', 'fBodyBodyGyroMag-sma()', 'tGravityAccMag-iqr()', 'tBodyAcc-mean()-Y', 'tBodyAcc-mean()-X', 'fBodyAcc-min()-Z', 'fBodyGyro-bandsEnergy()-25,32', 'tBodyGyroJerkMag-sma()', 'fBodyBodyAccJerkMag-max()', 'fBodyGyro-bandsEnergy()-57,64', 'fBodyAccJerk-bandsEnergy()-33,48.2', 'fBodyBodyGyroMag-mean()', 'fBodyAccMag-energy()', 'fBodyAccJerk-bandsEnergy()-25,48.2', 'tGravityAcc-iqr()-Z', 'fBodyBodyGyroJerkMag-energy()', 'fBodyAcc-bandsEnergy()-33,40.2', 'fBodyAcc-max()-X', 'fBodyAccMag-min()', 'tGravityAcc-mad()-X', 'fBodyAcc-mean()-Y', 'fBodyGyro-bandsEnergy()-49,56', 'tGravityAccMag-arCoeff()4', 'tGravityAccMag-sma()']
==================================================
Features excluded (this step):
['fBodyAcc-bandsEnergy()-25,48.2', 'tBodyAcc-mean()-Z', 'fBodyAcc-bandsEnergy()-25,32.2', 'fBodyAccJerk-bandsEnergy()-33,40.2', 'tGravityAcc-std()-X', 'tBodyAcc-mean()-Y', 'tBodyAcc-mean()-X', 'fBodyGyro-bandsEnergy()-25,32.1', 'fBodyGyro-bandsEnergy()-25,48.1', 'fBodyGyro-bandsEnergy()-33,40.2', 'fBodyGyro-bandsEnergy()-25,32', 'fBodyGyro-bandsEnergy()-25,48', 'fBodyGyro-bandsEnergy()-33,48.2', 'tGravityAcc-mad()-Y', 'fBodyGyro-bandsEnergy()-33,40.1', 'fBodyGyro-bandsEnergy()-57,64.1', 'fBodyGyro-bandsEnergy()-57,64', 'fBodyGyro-bandsEnergy()-49,64', 'tGravityAcc-std()-Y', 'Activity', 'fBodyGyro-bandsEnergy()-57,64.2', 'fBodyAccJerk-bandsEnergy()-33,48.2', 'fBodyGyro-bandsEnergy()-49,64.2', 'fBodyGyro-bandsEnergy()-25,32.2', 'fBodyGyro-bandsEnergy()-25,48.2', 'fBodyAccJerk-bandsEnergy()-57,64.1', 'fBodyAccJerk-bandsEnergy()-57,64', 'tGravityAcc-iqr()-Y', 'tGravityAcc-iqr()-Z', 'fBodyAccJerk-bandsEnergy()-25,48.2', 'fBodyAcc-bandsEnergy()-33,40.2', 'fBodyGyro-bandsEnergy()-33,48.1', 'tGravityAcc-mad()-X', 'fBodyAcc-bandsEnergy()-33,48.2', 'fBodyGyro-bandsEnergy()-41,48.1', 'subject', 'fBodyGyro-bandsEnergy()-49,56', 'fBodyGyro-bandsEnergy()-41,48.2', 'tGravityAcc-iqr()-X', 'fBodyGyro-bandsEnergy()-41,48', 'fBodyAccJerk-bandsEnergy()-57,64.2', 'fBodyAccJerk-bandsEnergy()-25,32.2']
==================================================
Removed total: 563 ---> 448 features
Total feature removal count: 115
==================================================
Removed this step: 490 ---> 448 features
Feature removal this step count: 42